/**
 * Evidence artifact types for the Evidence Artifact Viewer with Redaction States
 */

export type ArtifactType = 'image' | 'document' | 'text' | 'video' | 'audio';

export type RedactionLevel = 'none' | 'partial' | 'full' | 'custom';

export type RedactionRegion = {
  id: string;
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  width: number; // percentage 0-100
  height: number; // percentage 0-100
  reason?: string;
  createdAt: Date;
  createdBy: string;
};

export type ArtifactMetadata = {
  id: string;
  type: ArtifactType;
  filename: string;
  mimeType: string;
  size: number;
  uploadedAt: Date;
  uploadedBy: string;
  claimId?: string;
  verificationSessionId?: string;
  extractedText?: string;
  ocrConfidence?: number;
  piiDetected?: boolean;
  piiTypes?: string[];
};

export type RedactionState = {
  level: RedactionLevel;
  regions: RedactionRegion[];
  autoGeneratedRegions: RedactionRegion[];
  manuallyReviewedRegions: RedactionRegion[];
  lastModified: Date;
  modifiedBy: string;
  approvedBy?: string;
  approvedAt?: Date;
};

export type ViewingPermission = {
  canViewOriginal: boolean;
  canViewRedacted: boolean;
  canModifyRedactions: boolean;
  canApproveRedactions: boolean;
  role: 'admin' | 'operator' | 'reviewer' | 'viewer';
};

export type EvidenceArtifact = {
  id: string;
  metadata: ArtifactMetadata;
  content: string; // URL or base64 content
  thumbnail?: string;
  redactionState: RedactionState;
  permissions: ViewingPermission;
  verificationResult?: {
    score: number;
    confidence: number;
    riskLevel: 'low' | 'medium' | 'high';
  };
};

export type ViewMode = 'original' | 'redacted' | 'comparison';

export type ArtifactViewerState = {
  selectedArtifact: EvidenceArtifact | null;
  viewMode: ViewMode;
  zoomLevel: number;
  panPosition: { x: number; y: number };
  showRedactionOverlay: boolean;
  selectedRegions: string[];
  isEditingRedactions: boolean;
};

export type RedactionTool = {
  type: 'rectangle' | 'blur' | 'pixelate' | 'blackout';
  strength?: number; // for blur/pixelate
  reason: string;
  autoApply?: boolean;
};

export type PIIDetectionResult = {
  detected: boolean;
  regions: Array<{
    type: string;
    confidence: number;
    region: RedactionRegion;
  }>;
  processedAt: Date;
};

// Events for redaction state changes
export type RedactionEvent = {
  type: 'region_added' | 'region_removed' | 'region_modified' | 'level_changed' | 'approved' | 'rejected';
  artifactId: string;
  userId: string;
  timestamp: Date;
  data: Record<string, unknown>;
};
