/** @jest-environment jsdom */
import '@testing-library/jest-dom';
import { render, screen, fireEvent } from '@testing-library/react';
import { EvidenceArtifactViewer } from '../EvidenceArtifactViewer';
import type { EvidenceArtifact } from '@/types/evidence-artifact';

const mockArtifact: EvidenceArtifact = {
  id: 'test-artifact-1',
  metadata: {
    id: 'test-meta-1',
    type: 'image',
    filename: 'test-image.jpg',
    mimeType: 'image/jpeg',
    size: 1024000,
    uploadedAt: new Date('2024-01-01T00:00:00Z'),
    uploadedBy: 'test-user',
    piiDetected: false,
  },
  content: 'data:image/jpeg;base64,testdata',
  redactionState: {
    level: 'none',
    regions: [],
    autoGeneratedRegions: [],
    manuallyReviewedRegions: [],
    lastModified: new Date('2024-01-01T00:00:00Z'),
    modifiedBy: 'test-user',
  },
  permissions: {
    canViewOriginal: true,
    canViewRedacted: true,
    canModifyRedactions: true,
    canApproveRedactions: false,
    role: 'operator',
  },
};

describe('EvidenceArtifactViewer', () => {
  it('renders artifact information correctly', () => {
    render(<EvidenceArtifactViewer artifact={mockArtifact} />);

    expect(screen.getByText('test-image.jpg')).toBeInTheDocument();
    expect(screen.getByText((content, element) => {
      return element?.tagName.toLowerCase() === 'span' && content.includes('image') && content.includes('0.98 MB');
    })).toBeInTheDocument();
  });

  it('displays view mode controls based on permissions', () => {
    render(<EvidenceArtifactViewer artifact={mockArtifact} />);

    expect(screen.getByText('Original')).toBeInTheDocument();
    expect(screen.getByText('Redacted')).toBeInTheDocument();
    expect(screen.getByText('Compare')).toBeInTheDocument();
  });

  it('shows redaction controls when user has modify permissions', () => {
    render(<EvidenceArtifactViewer artifact={mockArtifact} />);

    expect(screen.getByText('Edit Redactions')).toBeInTheDocument();
  });

  it('displays metadata correctly', () => {
    render(<EvidenceArtifactViewer artifact={mockArtifact} />);

    expect(screen.getByText('1/1/2024')).toBeInTheDocument();
    expect(screen.getByText('none')).toBeInTheDocument();
    expect(screen.getByText('No')).toBeInTheDocument();
    expect(screen.getByText('0')).toBeInTheDocument();
  });

  it('handles view mode changes', () => {
    render(<EvidenceArtifactViewer artifact={mockArtifact} />);

    const redactedButton = screen.getByText('Redacted');
    fireEvent.click(redactedButton);

    expect(redactedButton).toHaveClass('bg-blue-500');
  });

  it('handles zoom controls', () => {
    render(<EvidenceArtifactViewer artifact={mockArtifact} />);

    const zoomInButton = screen.getByRole('button', { name: /zoom in/i });
    const zoomOutButton = screen.getByRole('button', { name: /zoom out/i });
    const resetButton = screen.getByRole('button', { name: /reset/i });

    expect(zoomInButton).toBeInTheDocument();
    expect(zoomOutButton).toBeInTheDocument();
    expect(resetButton).toBeInTheDocument();
  });

  describe('with restricted permissions', () => {
    const restrictedArtifact: EvidenceArtifact = {
      ...mockArtifact,
      permissions: {
        canViewOriginal: false,
        canViewRedacted: true,
        canModifyRedactions: false,
        canApproveRedactions: false,
        role: 'viewer',
      },
    };

    it('hides original view when no permission', () => {
      render(<EvidenceArtifactViewer artifact={restrictedArtifact} />);

      expect(screen.queryByText('Original')).not.toBeInTheDocument();
      expect(screen.getByText('Redacted')).toBeInTheDocument();
    });

    it('hides edit controls when no modify permission', () => {
      render(<EvidenceArtifactViewer artifact={restrictedArtifact} />);

      expect(screen.queryByText('Edit Redactions')).not.toBeInTheDocument();
    });
  });

  describe('with redaction regions', () => {
    const artifactWithRedactions: EvidenceArtifact = {
      ...mockArtifact,
      redactionState: {
        ...mockArtifact.redactionState,
        level: 'partial',
        regions: [
          {
            id: 'region-1',
            x: 10,
            y: 10,
            width: 20,
            height: 15,
            reason: 'Test redaction',
            createdAt: new Date('2024-01-01T00:00:00Z'),
            createdBy: 'test-user',
          },
        ],
      },
    };

    it('displays redaction statistics correctly', () => {
      render(<EvidenceArtifactViewer artifact={artifactWithRedactions} />);

      expect(screen.getByText('partial')).toBeInTheDocument();
      expect(screen.getByText('1')).toBeInTheDocument();
    });
  });

  describe('PII detection', () => {
    const artifactWithPII: EvidenceArtifact = {
      ...mockArtifact,
      metadata: {
        ...mockArtifact.metadata,
        piiDetected: true,
        piiTypes: ['email', 'phone'],
      },
    };

    it('shows PII detected status', () => {
      render(<EvidenceArtifactViewer artifact={artifactWithPII} />);

      expect(screen.getByText('Yes')).toBeInTheDocument();
    });
  });
});
