#!/usr/bin/env python3
"""Register a Soroban deployment in deployments/registry.json and write a markdown record."""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import date
from pathlib import Path


def wasm_hash_hex(wasm_path: Path) -> str:
    digest = hashlib.sha256(wasm_path.read_bytes()).hexdigest()
    return digest


def load_registry(path: Path) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {
        "schema_version": 1,
        "contract": "aid_escrow",
        "deployments": [],
    }


def write_markdown_record(
    record_path: Path,
    *,
    contract_name: str,
    version: str,
    network: str,
    contract_id: str,
    wasm_hash: str,
    deployer: str | None,
    version_tag: str,
) -> None:
    record_path.parent.mkdir(parents=True, exist_ok=True)
    deployer_line = deployer or "(see deploy output)"
    content = f"""# {network.title()} Deployment Record — {date.today().isoformat()}

> Canonical record of the {contract_name} v{version} deployment to Stellar {network.title()}.
> Generated by `scripts/register-deployment.py`.

## Deployment Summary

| Field              | Value |
| :----------------- | :---- |
| **Contract ID**    | `{contract_id}` |
| **WASM Hash**      | `{wasm_hash}` |
| **Deployer**       | `{deployer_line}` |
| **Contract Crate** | `{contract_name} v{version}` |
| **Network**        | {network.title()} |
| **Version Tag**    | `{version_tag}` |
| **Deployed At**    | {date.today().isoformat()} |

## Required `.env` Values

```bash
CONTRACT_ID={contract_id}
CONTRACT_VERSION={version}
NETWORK={network}
```

## Verification

```bash
./scripts/testnet-invoke.sh get-admin --contract-id {contract_id}

stellar contract invoke \\
  --id {contract_id} \\
  --network {network} \\
  -- contract_version
```

Expected `contract_version`: `{version}`
"""
    record_path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Register aid_escrow deployment")
    parser.add_argument("--project-dir", required=True)
    parser.add_argument("--contract-name", default="aid_escrow")
    parser.add_argument("--contract-id", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--network", default="testnet")
    parser.add_argument("--wasm", required=True)
    parser.add_argument("--deployer", default="")
    args = parser.parse_args()

    project_dir = Path(args.project_dir)
    registry_path = project_dir / "deployments" / "registry.json"
    wasm_path = Path(args.wasm)
    if not wasm_path.is_absolute():
        wasm_path = project_dir / wasm_path

    digest = wasm_hash_hex(wasm_path)
    version_tag = f"v{args.version}-{args.network}"
    deployed_at = date.today().isoformat()
    record_name = f"{args.network}-{deployed_at}.md"
    record_rel = f"deployments/{record_name}"

    registry = load_registry(registry_path)
    registry["contract"] = args.contract_name

    entry = {
        "network": args.network,
        "version": args.version,
        "contract_id": args.contract_id,
        "wasm_hash": digest,
        "deployer": args.deployer or None,
        "deployed_at": deployed_at,
        "version_tag": version_tag,
        "record": record_rel,
    }

    registry["deployments"] = [
        d
        for d in registry.get("deployments", [])
        if not (
            d.get("network") == args.network
            and d.get("version") == args.version
            and d.get("contract_id") == args.contract_id
        )
    ]
    registry["deployments"].append(entry)
    registry["deployments"].sort(key=lambda d: d.get("deployed_at", ""))

    registry_path.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")

    record_path = project_dir / record_rel
    write_markdown_record(
        record_path,
        contract_name=args.contract_name,
        version=args.version,
        network=args.network,
        contract_id=args.contract_id,
        wasm_hash=digest,
        deployer=args.deployer or None,
        version_tag=version_tag,
    )

    print(f"REGISTRY={registry_path}")
    print(f"RECORD={record_path}")
    print(f"VERSION_TAG={version_tag}")
    print(f"WASM_HASH={digest}")


if __name__ == "__main__":
    main()
